import { IFullProductInfo } from "@/store/product/types";

export const data: IFullProductInfo[] = [
  {
    id: 1,
    name: "Футболка оверсайз",
    brand: "BasicWear",
    description: "Модная oversize футболка из 100% хлопка.",
    category: ["Одежда", "Женская одежда", "Футболки"],
    price: 2499,
    isFavorite: true,
    image: "https://picsum.photos/id/1/400/500",
  },
  {
    id: 2,
    name: "Джинсы скинни",
    brand: "DenimCo",
    description: "Узкие джинсы с высокой посадкой, стрейчевая ткань.",
    category: ["Одежда", "Женская одежда", "Джинсы"],
    price: 4599,
    isFavorite: false,
    image: "https://picsum.photos/id/2/400/500",
  },
  {
    id: 3,
    name: "Кроссовки беговые",
    brand: "RunPro",
    description: "Легкие кроссовки для бега с амортизацией.",
    category: ["Обувь", "Спортивная обувь", "Кроссовки"],
    price: 5999,
    isFavorite: true,
    image: "https://picsum.photos/id/3/400/500",
  },
  {
    id: 4,
    name: "Свитшот худи",
    brand: "StreetStyle",
    description: "Теплый худи из мягкого футера, с капюшоном.",
    category: ["Одежда", "Мужская одежда", "Худи"],
    price: 3299,
    isFavorite: false,
    image: "https://picsum.photos/id/4/400/500",
  },
  {
    id: 5,
    name: "Платье миди",
    brand: "Elegance",
    description: "Элегантное платье миди с цветочным принтом.",
    category: ["Одежда", "Женская одежда", "Платья"],
    price: 5199,
    isFavorite: true,
    image: "https://picsum.photos/id/5/400/500",
  },
  {
    id: 6,
    name: "Рюкзак городской",
    brand: "UrbanGear",
    description: "Вместительный рюкзак с отделением для ноутбука.",
    category: ["Аксессуары", "Сумки", "Рюкзаки"],
    price: 3899,
    isFavorite: false,
    image: "https://picsum.photos/id/6/400/500",
  },
  {
    id: 7,
    name: "Куртка джинсовая",
    brand: "DenimCo",
    description: "Классическая джинсовая куртка прямого кроя.",
    category: ["Одежда", "Верхняя одежда", "Куртки"],
    price: 6299,
    isFavorite: true,
    image: "https://picsum.photos/id/7/400/500",
  },
  {
    id: 8,
    name: "Брюки классические",
    brand: "OfficeStyle",
    description: "Деловые брюки со стрелками, состав: шерсть 80%.",
    category: ["Одежда", "Мужская одежда", "Брюки"],
    price: 4899,
    isFavorite: false,
    image: "https://picsum.photos/id/8/400/500",
  },
  {
    id: 9,
    name: "Кепка бейсболка",
    brand: "SportLife",
    description: "Бейсболка с регулируемой застежкой, 100% хлопок.",
    category: ["Аксессуары", "Головные уборы", "Кепки"],
    price: 1299,
    isFavorite: true,
    image: "https://picsum.photos/id/9/400/500",
  },
  {
    id: 10,
    name: "Юбка карандаш",
    brand: "Elegance",
    description: "Приталенная юбка-карандаш для офиса и вечера.",
    category: ["Одежда", "Женская одежда", "Юбки"],
    price: 3599,
    isFavorite: false,
    image: "https://picsum.photos/id/10/400/500",
  },
];
